// Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
// For details: https://github.com/Withered-Flower-0422/BST/blob/main/LICENSE

declare module "game:type" {
    type EaseType =
        | "Linear"
        | "Spring"
        | "EaseInQuad"
        | "EaseOutQuad"
        | "EaseInOutQuad"
        | "EaseInCubic"
        | "EaseOutCubic"
        | "EaseInOutCubic"
        | "EaseInQuart"
        | "EaseOutQuart"
        | "EaseInOutQuart"
        | "EaseInQuint"
        | "EaseOutQuint"
        | "EaseInOutQuint"
        | "EaseInSine"
        | "EaseOutSine"
        | "EaseInOutSine"
        | "EaseInExpo"
        | "EaseOutExpo"
        | "EaseInOutExpo"
        | "EaseInCirc"
        | "EaseOutCirc"
        | "EaseInOutCirc"
        | "EaseInBounce"
        | "EaseOutBounce"
        | "EaseInOutBounce"
        | "EaseInBack"
        | "EaseOutBack"
        | "EaseInOutBack"
        | "EaseInElastic"
        | "EaseOutElastic"
        | "EaseInOutElastic"
}
